
services:
  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    container_name: productapi
    build:
      context: ./ProductApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
       condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
       MYSQL_ROOT_PASSWORD: gokstad
       MYSQL_DATABASE: product-db
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
 
volumes:
  mysql_data: