
services:
  productapi:
    image: renatehem/eksamen:productapi-v1
    container_name: productapi
    build:
      context: ./ProductApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
       condition: service_healthy
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
       MYSQL_ROOT_PASSWORD: gokstad
       MYSQL_DATABASE: product-db
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 10s

  
  nginx:
    image: renatehem/eksamen:nginx-v1
    container_name: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - productapi
    networks:
      - backend

volumes:
  mysql_data:
  
networks:
  backend:    